// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered text optimizer for project descriptions and resume summaries.
 *
 * - optimizeProjectDescription - A function that refines user-provided text for professional appeal.
 * - OptimizeProjectDescriptionInput - The input type for the optimizeProjectDescription function.
 * - OptimizeProjectDescriptionOutput - The return type for the optimizeProjectDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OptimizeProjectDescriptionInputSchema = z.object({
  text: z
    .string()
    .describe(
      'The text to be optimized. This could be a project description or a resume summary.'
    ),
});
export type OptimizeProjectDescriptionInput = z.infer<
  typeof OptimizeProjectDescriptionInputSchema
>;

const OptimizeProjectDescriptionOutputSchema = z.object({
  optimizedText: z
    .string()
    .describe('The AI-optimized version of the input text.'),
});
export type OptimizeProjectDescriptionOutput = z.infer<
  typeof OptimizeProjectDescriptionOutputSchema
>;

export async function optimizeProjectDescription(
  input: OptimizeProjectDescriptionInput
): Promise<OptimizeProjectDescriptionOutput> {
  return optimizeProjectDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'optimizeProjectDescriptionPrompt',
  input: {schema: OptimizeProjectDescriptionInputSchema},
  output: {schema: OptimizeProjectDescriptionOutputSchema},
  prompt: `You are an AI-powered text optimizer specializing in refining project descriptions and resume summaries.

  Your goal is to make the text more compelling and attractive to potential employers or clients.
  Focus on improving clarity, impact, and professionalism.

  Original Text: {{{text}}}

  Optimized Text:`, // The AI will generate the optimized text here
});

const optimizeProjectDescriptionFlow = ai.defineFlow(
  {
    name: 'optimizeProjectDescriptionFlow',
    inputSchema: OptimizeProjectDescriptionInputSchema,
    outputSchema: OptimizeProjectDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
